name: Send to production

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write
  
concurrency:
  group: 'production'
  cancel-in-progress: true

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "VITE_BASE_URL=${{ github.event.repository.name }}" >> .env
          cat .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: dist
          name: artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.4
        id: pages

      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: artifact